GET http://localhost:3001/todos

###
GET http://localhost:3001/todos/64f1fd3e33ca447971055382

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"Deliver Pizza"
}


###
PUT http://localhost:3001/todo/edit/64f1fd3e33ca447971055382
Content-Type: application/json

{
    "text": "Physics",
    "name": "Awais",
    "degree": "Software Engineering 2",
    "university": "UET"
}


###

DELETE http://localhost:3001/todo/delete/64ecd5020acced1127fd742e
###
PUT http://localhost:3001/todo/complete/64ecb58df900f99495517ed9


###